const ACTIONS = {
  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  REMOVE_FROM_CART: 'REMOVE_TO_CART',
  UPDATE_AMOUNT_REQUEST: 'UPDATE_AMOUNT_REQUEST',
  UPDATE_AMOUNT_SUCCESS: 'UPDATE_AMOUNT_SUCCESS',
};

export default ACTIONS;
